chore(deps): upgrade `ember-cli@~4.1.0`
Fixes this runtime error:

> ReferenceError: Ember is not defined

Caused by this LOC:

```js
<script>Ember.assert('The tests file was not loaded. Make sure your tests index.html includes "assets/tests.js".', EmberENV.TESTS_FILE_LOADED);</script>
```